apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-scanner-deployment
  labels:
    app: network-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-scanner
  template:
    metadata:
      labels:
        app: network-scanner
    spec:
      containers:
        - name: network-scanner
          image: namishc/network-scanner:v3
          imagePullPolicy: Always
          command: ["python3", "nw_scanner.py"]
          args: ["192.168.0.0/24"] 
      imagePullSecrets:
        - name: registrycreds
