apiVersion: batch/v1
kind: CronJob
metadata:
  name: network-scanner-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: network-scanner
              image: namishc/network-scanner:v3
              imagePullPolicy: Always
              command: ["python3", "nw_scanner.py"]
              args: ["192.168.0.0/24"]  
        restartPolicy: OnFailure
        imagePullSecrets:
          - name: registrycreds
