---
- hosts: all
  become: true

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install prerequisites
      apt:
        pkg: "{{ item }}"
        state: latest
        update_cache: true
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - software-properties-common

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker and additional components
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin
        
    - name: Copy syslog configuration file
      copy:
        src: utils/syslog.json
        dest: /etc/docker/syslog.json
        owner: root
        group: root
        mode: '0644'

    - name: Add user to the docker group
      user:
        name: ubuntu # Or any current user
        groups: docker
        append: yes

    - name: Start Docker and enable at boot
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true